### ISSUE TITLE
AddIPFSHash() 함수 호출 -> 에러 발생 (No valid response from any peers) 

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [Choi-Jiwon-38/Delivery#4]
아래와 같은 에러 상황이 발생

https://github.com/Choi-Jiwon-38/Delivery/blob/f4a255bef006942c4d44fa1d1c99cf5e967cd47d/deliveryapp/deliverytest.js#L43
https://github.com/Choi-Jiwon-38/Delivery/blob/f4a255bef006942c4d44fa1d1c99cf5e967cd47d/deliveryapp/deliverytest.js#L254

> error: [Transaction]: Error: No valid responses from any peers. Errors:
>     peer=peer0.org2.example.com:9051, status=500, message=delivery is not defined
>     peer=peer0.org1.example.com:7051, status=500, message=delivery is not defined
>     at newEndorsementError (/root/delivery/deliveryapp/node_modules/fabric-network/lib/transaction.js:74:12)
>     at getResponsePayload (/root/delivery/deliveryapp/node_modules/fabric-network/lib/transaction.js:41:23)
>     at Transaction.submit (/root/delivery/deliveryapp/node_modules/fabric-network/lib/transaction.js:255:28)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async AddIPFSHash (/root/delivery/deliveryapp/deliverytest.js:43:9)
>     at async /root/delivery/deliveryapp/deliverytest.js:254:6
> Failed to submit transaction: Error: No valid responses from any peers. Errors:
>     peer=peer0.org2.example.com:9051, status=500, message=delivery is not defined
>     peer=peer0.org1.example.com:7051, status=500, message=delivery is not defined

**Comment by Choi-Jiwon-38** [comment]
chaincode 부분에서 delivery가 정의되지 않은 채로 value가 할당되고 있어서 발생했던 문제
